/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'fkautz' at '7/13/14 6:04 PM' with Gradle 2.0
 *
 * @author fkautz, @date 7/13/14 6:04 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
