/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'fkautz' at '7/13/14 11:31 PM' with Gradle 2.0
 *
 * @author fkautz, @date 7/13/14 11:31 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
